### ISSUE TITLE
唐風的視頻聲音太小

### ISSUE THREAD

**Issue by tonghuix** [COSCUP/staff-handbook#4]
如題。同時演講超過40分鐘，可能沒有人耐心看完40分鐘。

建議是否可以換成Mosky的TED演講：https://www.youtube.com/watch?v=4_N2-fXjwEU

**Comment by bobchao** [comment]
可以同場加映呀，來個 PR 如何？

**Comment by tonghuix** [comment]
已發 https://github.com/COSCUP/staff-handbook/pull/5

**Comment by bobchao** [comment]
thanks~
